repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: detect-private-key
  -   repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
        - id: black
          args:
            - kubesync
  -   repo: local
      hooks:
        -   id: mypy
            name: mypy
            entry: python -m mypy
            language: system
            pass_filenames: false
        -   id: pylint
            name: pylint
            entry: pylint kubesync
            language: system
            pass_filenames: false
        -   id: isort
            name: isort
            entry: isort -rc .
            language: system
            pass_filenames: false
